# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



minimal_mistakes_skin    : mint # contrast # "default"

# Site settings
locale                   : "zh-CN"
title                    : "技术博客"
title-separator          : "-"
subtitle                 : "一名交通模数师的日常"
name                     : "tianchaoyu"
description              : "交通模型与仿真知识实践"
email                    : tianchaoyu@gmail.com
baseurl                  : "" # the subpath of your site, e.g. /blog
url                      : "" # the base hostname & protocol for your site, e.g. http://example.com
og_image                 : /assets/images/site-logo.jpg
timezone                 : Asia/Shanghai
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-EMB5R38212"
    anonymize_ip         : false # default
comments:
  provider               : "disqus"
  disqus:
    shortname            : 'tianchaoyu-github-io'
author:
  name                   : "tianchaoyu"
  avatar                 : "/assets/images/site-logo.jpg"
  bio                    : "交通模数师"
  location               : "深圳"
  email                  : "tianchaoyu@gmail.com"
  links:
    - label              : "Github"
      icon               : "fab fa-fw fa-github"
      url                : "https://github.com/tianchaoyu"
    - label              : "CSDN"
      url                : "https://blog.csdn.net/_tianchaoyu_"

footer:
  links:
    - label              : "Github"
      icon               : "fab fa-fw fa-github"
      url                : "https://github.com/tianchaoyu"

include:
  - _pages

# Search
search                   : true
lunr:
  search_within_pages    : true
  search_full_content    : false

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: emme
    values:
      layout: single
      toc: true
      toc_label: '目录'
      toc_sticky: true
      sidebar:
        nav: "emme"

  # _posts
  - scope:
      path: ""
      type: python
    values:
      layout: single
      toc: true
      toc_label: '目录'
      toc_sticky: true
      sidebar:
        nav: "python"



# Collections
collections:
  emme:
    output: true
    sort_by: lesson
    permalink: /tutorials/:collection/:path/

  python:
    output: true
    sort_by: lesson
    permalink: /tutorials/:collection/:path/



# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

markdown: kramdown
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
